### ISSUE TITLE
Add to space toolbar

### ISSUE THREAD

**Issue by jaisekjames** [ftassy/WhatsApp-Web-in-Thunderbird#1]
It will be very nice, if it can be added to space tool bar in TB102

**Comment by ftassy** [comment]
Thanks for the suggestion, I will definitely add it !

**Comment by ftassy** [comment]
Done in https://github.com/ftassy/WhatsApp-Web-in-Thunderbird/pull/2 and add-on version 1.1.0 🙂  
Would you like to try and confirm that it works fine for you ?

**Comment by jaisekjames** [comment]
Thank you
